export enum GameAction {
    MOVE_PAWN = "MOVE_PAWN",
    RELEASE_PAWN = "RELEASE_PAWN",
    ROLL = "ROLL",
    CHAT = "CHAT",
    OUT_OF_TIME = "OUT_OF_TIME",
    DISCONNECT = "DISCONNECT",
    RECONNECT = "RECONNECT",
    EXIT_GAME = "EXIT_GAME"
}
